### ISSUE TITLE
Prefix handles when enqueuing CSS and JS

### ISSUE THREAD

**Issue by mandiwise** [redacademy/catalyst-winter-2017#100]
Always add a unique prefix to the first argument passed into `wp_enqueue_style` or `wp_enqueue_script`. For example, this:

```
wp_enqueue_script('flickity', ...
```

Should be this:

```
wp_enqueue_script('catalyst-flickity', ...
```

Again, helps avoid potential naming collisions in the future!

**Comment by mr-moto** [comment]
fixed
