### ISSUE TITLE
Remove "custom field" support where CPTs are registered

### ISSUE THREAD

**Issue by mandiwise** [redacademy/catalyst-winter-2017#102]
Please remove support for "custom fields" on your post types, for example, this:

```
$args = array(
  // ...
  'supports'  => array( 'title', 'editor', 'thumbnail', 'revisions', 'custom-fields', ),
  // ...
```

Should look like this:

```
$args = array(
  // ...
  'supports'  => array( 'title', 'editor', 'thumbnail', 'revisions' ),
  // ...
```

The "custom fields" are you enabling here are a legacy thing in WP...Custom Field Suite provides all the UI we need for adding this data.

**Comment by suleee** [comment]
I remove all the "custom fields" on the post types
