### ISSUE TITLE
Don't over-nest selectors in CSS

### ISSUE THREAD

**Issue by mandiwise** [redacademy/catalyst-winter-2017#109]
This is way too specific:

```
.container .desktop-menu #primary-menu li.current-menu-item a { }
```

Please audit all of your Sass partials, and reduce specificity wherever you can. Even just making a passing glance I can see that there is a lot of potential for this throughout your CSS!

**Comment by mr-moto** [comment]
checked for overnesting in 
* 404
* contact
* front
* projects
* single projects
* submit

**Comment by suleee** [comment]
Checked 
* our-story
* new-media
* footer
* navigation

**Comment by mr-moto** [comment]
fixed
